--------------------------------------------------------------------------
--script for auto_funcs.h and auto_funcs.cpp generation
--expects LuaJIT
--------------------------------------------------------------------------
--load parser module
package.path = package.path..";../../cimgui/generator/?.lua"
local cpp2ffi = require"cpp2ffi"
local save_data = cpp2ffi.save_data
local copyfile = cpp2ffi.copyfile
--take script args---------------------------
local COMPILER, CPRE, INTERNAL_GENERATION, COMMENTS_GENERATION = cpp2ffi.GetScriptArgs({},...)
--------------------------------------------------------------------------
--this table has the functions to be skipped in generation
--------------------------------------------------------------------------
local cimgui_manuals = {
    -- igLogText = true,
    -- ImGuiTextBuffer_appendf = true,
}
--this table will provide string substitutions
local str_subst = {
	ImNodesStyleVar_GridSpacing = "ImNodesStyleVar_GridSpacing_r", --to avoid name collision with Nelarius/imnodees
	ImNodesStyleVar_COUNT = "ImNodesStyleVar_COUNT_r"
}
--------------------------------------------------------------------------
--this table is a dictionary to force a naming of function overloading (instead of algorythmic generated)
--first level is cimguiname without postfix, second level is the signature of the function, value is the
--desired name
---------------------------------------------------------------------------
local cimgui_overloads = {
    --igPushID = {
        --["(const char*)"] =           "igPushIDStr",
        --["(const char*,const char*)"] = "igPushIDRange",
        --["(const void*)"] =           "igPushIDPtr",
        --["(int)"] =                   "igPushIDInt"
    --},
}

--------------------------header definitions
local cimgui_header = 
[[//This file is automatically generated by generator.lua from https://github.com/cimgui/cimnodes_r
//based on ImNodes.h file version XXX from https://github.com/rokups/ImNodes
]]
--------------------------------------------------------------------------
--helper functions
--------------------------------functions for C generation
--load parser module
package.path = package.path..";../../cimgui/generator/?.lua"
local cpp2ffi = require"cpp2ffi"
local copyfile = cpp2ffi.copyfile

--------------------------------------------------------
-----------------------------do it----------------------
--------------------------------------------------------

-------------funtion for parsing ImNodes headers
local function parseImGuiHeader(header,names,modulename)
	--prepare parser
	local parser = cpp2ffi.Parser()
	parser.modulename = modulename
	parser.getCname = function(stname,funcname,namespace)
		if namespace then namespace = namespace:gsub("::","_") end
		local pre = (stname == "") and (namespace and (namespace=="ImGui" and "ig" or namespace.."_") or "ig") or stname.."_"
		return pre..funcname
	end
	parser.cname_overloads = cimgui_overloads
	parser:set_manuals(cimgui_manuals, modulename)
	--parser.UDTs = {"ImVec2","ImVec4","ImColor","ImRect"}
	parser.cimgui_inherited =  dofile([[../../cimgui/generator/output/structs_and_enums.lua]])
	parser.str_subst = str_subst
	
	local include_cmd = COMPILER=="cl" and [[ /I ]] or [[ -I ]]
	local extra_includes = include_cmd.." ../../cimgui/imgui ".." -x c++ " --force c++ compiling with gcc (Tp for cl?)
	
	parser:take_lines(CPRE..extra_includes..header, names, COMPILER)
	
	return parser
end
--generation
print("------------------generation with "..COMPILER.."------------------------")
local modulename = "cimnodes_r"
local parser1 = parseImGuiHeader([[../ImNodes/ImNodesEz.h]],{[[ImNodes]],[[ImNodesEz]]},modulename)
parser1:do_parse()
parser1:cimgui_generation(cimgui_header)
parser1:save_output()

print"all done!!"
